package api

// countryNameToCode is the map the v1 /countries endpoint returns.
//
// It is reproduced from the upstream service unchanged, including entries that
// map an overseas territory onto its metropolitan country code, because
// clients compare this response and a correction here would be a breaking
// change for them. The v2 endpoint returns the registry instead.
var countryNameToCode = map[string]string{
	"Albania":                   "AL",
	"Algeria":                   "DZ",
	"Andorra":                   "AD",
	"Angola":                    "AO",
	"Austria":                   "AT",
	"Azerbaijan":                "AZ",
	"Bahrain":                   "BH",
	"Belgium":                   "BE",
	"Benin":                     "BJ",
	"Bosnia and Herzegovina":    "BA",
	"Brazil":                    "BR",
	"British Virgin Islands":    "VG",
	"Bulgaria":                  "BG",
	"Burkina Faso":              "BF",
	"Burundi":                   "BI",
	"Cameroon":                  "CM",
	"Cape Verde":                "CV",
	"Central African Republic":  "FR",
	"Congo":                     "CG",
	"Costa Rica":                "CR",
	"Croatia":                   "HR",
	"Cyprus":                    "CY",
	"Czech Republic":            "CZ",
	"Denmark":                   "DK",
	"Dominican Republic":        "DO",
	"Egypt":                     "EG",
	"Estonia":                   "EE",
	"Faroe Islands":             "FO",
	"Finland":                   "FI",
	"France":                    "FR",
	"French Guiana":             "FR",
	"French Polynesia":          "FR",
	"Gabon":                     "GA",
	"Georgia":                   "GE",
	"Germany":                   "DE",
	"Gibraltar":                 "GI",
	"Greece":                    "GR",
	"Greenland":                 "GL",
	"Guadeloupe":                "FR",
	"Guatemala":                 "GT",
	"Guernsey":                  "GB",
	"Hungary":                   "HU",
	"Iceland":                   "IS",
	"Iran":                      "IR",
	"Ireland":                   "IE",
	"Isle of Man":               "GB",
	"Israel":                    "IL",
	"Italy":                     "IT",
	"Ivory Coast":               "CI",
	"Jersey":                    "GB",
	"Kazakhstan":                "KZ",
	"Kuwait":                    "KW",
	"Latvia":                    "LV",
	"Lebanon":                   "LB",
	"Liechtenstein":             "LI",
	"Lithuania":                 "LT",
	"Luxembourg":                "LU",
	"Macedonia":                 "MK",
	"Madagascar":                "MG",
	"Mali":                      "ML",
	"Malta":                     "MT",
	"Martinique":                "FR",
	"Mauritania":                "MR",
	"Mauritius":                 "MU",
	"Moldova":                   "MD",
	"Monaco":                    "MC",
	"Montenegro":                "ME",
	"Mozambique":                "MZ",
	"Netherlands":               "NL",
	"New Caledonia":             "FR",
	"Norway":                    "NO",
	"Pakistan":                  "PK",
	"Palestine, State of":       "PS",
	"Poland":                    "PL",
	"Portugal":                  "PT",
	"Romania":                   "RO",
	"Réunion":                   "FR",
	"Saint-Pierre and Miquelon": "FR",
	"San Marino":                "SM",
	"Sao Tome and Principe":     "PT",
	"Saudi Arabia":              "SA",
	"Senegal":                   "SN",
	"Serbia":                    "RS",
	"Slovakia":                  "SK",
	"Slovenia":                  "SI",
	"Spain":                     "ES",
	"Sweden":                    "SE",
	"Switzerland":               "CH",
	"Tunisia":                   "TN",
	"Turkey":                    "TR",
	"Ukraine":                   "UA",
	"United Arab Emirates":      "AE",
	"United Kingdom":            "GB",
	"Wallis and Futuna":         "FR",
}
